version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - needs-triage
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@types/*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github_actions
      - needs-triage
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
